[supabase]
url = "https://igbzclkhwnxnypjssdwz.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnYnpjbGtod254bnlwanNzZHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMzExNTcsImV4cCI6MjA4MTkwNzE1N30.Rwv-g0aLFWr6rLqIpGnvtGWhN1EEOwEOkQqlcT2-WAY"
